# =================================================
# Config for config.py
# =================================================

github:
  repos:

    - owner: Pytorch
      repo: Pytorch
      path: torch

jsonl_database_path: data/docs_en_2023_12_20.jsonl
