# config file to simulate the prompt storage

general:
  versions:

    - version_id: 0.0.0
      supplier: openai
      system: "Act as a machine learning expert specialized on deep learning using pretrained models for image detection
       based on pre trained recent huggingface models on pytorch, take into account technical documentation from
       the different libraries and published papers: {technical_documentation}"
      technical_documentation: "The more similar content available on pytorch library is {3_nn_docs}"
      model: gpt-3.5-turbo-16k-0613
      temperature: 0
      max_length: 8000
      max_tokens: 8958
      top_p: 1
      frequency_penalty: 0
      presence_penalty: 0

    - version_id: 0.0.1
      supplier: openai
      system: "Act as a machine learning expert specialized on deep learning using pretrained models for image detection
       based on pre trained recent huggingface models on pytorch, take into account technical documentation from
       the different libraries and published papers: {technical_documentation}"
      technical_documentation: "The more similar content available on pytorch library is {3_nn_docs}"
      model: gpt-3.5-turbo
      temperature: 0
      max_length: 250
      max_tokens: 83
      top_p: 1
      frequency_penalty: 0
      presence_penalty: 0
